### ISSUE TITLE
addSampleData() broken?

### ISSUE THREAD

**Issue by ferreira-scm** [derele/MultiAmplicon#7] opened 2021-01-25 10:40 UTC
`blastTaxAnnot()` runs fine.
When adding sample data to MA: `addSampleData(MA, sample.data)` --> I have the following error:

"Error in attributes(value) <- supplied : 
length of 'dimnames' [1] not equal to array extent"

does addSampleData() still exist? Or should we now add the metadata directly into the phyloseq object?
`PS@sam_data <- sample_data(sample.data)` --> this works fine.

**Comment by derele** [comment] 2021-01-25 10:45
It should work in MA to make passing on the sample data seamless.

What is in `colnames(MA)` and in` getSampleData(MA)` before you add more? And in `rownames` of what you add?

What happens if you `addSampleData(MA)` (leaving the `sample.data` argument at its NULL default.)

**Comment by ferreira-scm** [comment] 2021-01-25 11:05
`head(colnames(MA))` --> a list with my sample names
[1] "AA_0333" "AA_0197" "AA_0089" "AA_0058" "SK_3023" "SK_3003"

`head(rownames(sample.data))` --> a list with my samples
[1] "AA_0048" "AA_0049" "AA_0050" "AA_0052" "AA_0053" "AA_0054"

`getSampleData(MA)`
Error in getSampleData(MA) : could not find function "getSampleData"

`head(MA@sampleData)`
Sample Data:        [6 samples by 2 sample variables]:
                                                                            readsF                                                                                                                                
 AA_0333 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0333_F_filt.fastq.gz                                                                                                                                
 AA_0197 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0197_F_filt.fastq.gz                                                                                                                                
 AA_0089 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0089_F_filt.fastq.gz                                                                                                                                
 AA_0058 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0058_F_filt.fastq.gz                                                                                                                                
 SK_3023 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/SK_3023_F_filt.fastq.gz                                                                                                                                
 SK_3003 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/SK_3003_F_filt.fastq.gz                                                                                                                                
                                                                             readsR                                                                                                                                
 AA_0333 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0333_F_filt.fastq.gz                                                                                                                                
 AA_0197 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0197_F_filt.fastq.gz                                                                                                                                
 AA_0089 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0089_F_filt.fastq.gz                                                                                                                                
 AA_0058 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/AA_0058_F_filt.fastq.gz                                                                                                                                
 SK_3023 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/SK_3023_F_filt.fastq.gz                                                                                                                                
 SK_3003 /SAN/Susanas_den/gitProj/HMHZ/tmp/run1/filtered1_1/SK_3003_F_filt.fastq.gz

`MAsampleData(MA)` --> nothing happens
`head(MAsample@sampleData)` --> same output as MA@sampleData

**Comment by derele** [comment] 2021-01-25 12:16
MA@sampleData doesn't have rownames? They need to be the same as `colnames(MA)` and `rownames(sample.data)` .If that's not the case the package should have produced an error before (and I'd need to fix that).

**Comment by ferreira-scm** [comment] 2021-01-25 12:51
`head(rownames(MA@sampleData))`
[1] "AA_0333" "AA_0197" "AA_0089" "AA_0058" "SK_3023" "SK_3003"

They look good!

**Comment by derele** [comment] 2021-01-25 14:13
Yes, looks like a fault in the package. I'll write a test to reproduce it tomorrow and fix it (today I'm with the kids and this is beyond what I can concentrate on a their current mood). 
Thanks for reporting!

**Comment by derele** [comment] 2021-02-04 07:32
This is ongoing. I'll make it a generic function that can work on MultiAmplicon or phyloseq objects equally.

**Comment by derele** [comment] 2023-10-05 10:55
This has been solved. Closing it with delay... because ... mhhh... academia ;-)

**Closed as completed** 2023-10-05 10:55 UTC
